#ifndef __CONSOLEDRAW_H__
#define __CONSOLEDRAW_H__

#include <Windows.h>
#include <stdio.h>

#define CD_BG_WHITE		(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE)
#define CD_BG_RED		BACKGROUND_RED
#define CD_BG_YELLOW	(BACKGROUND_RED | BACKGROUND_GREEN)
#define CD_BG_GREEN		BACKGROUND_GREEN
#define CD_BG_CYAN		(BACKGROUND_GREEN | BACKGROUND_BLUE)
#define CD_BG_BLUE		BACKGROUND_BLUE
#define CD_BG_VIOLET	(BACKGROUND_BLUE | BACKGROUND_RED)
#define CD_BG_INTENSE	BACKGROUND_INTENSITY

#define CD_FG_WHITE		(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE)
#define CD_FG_RED		FOREGROUND_RED
#define CD_FG_YELLOW	(FOREGROUND_RED | FOREGROUND_GREEN)
#define CD_FG_GREEN		FOREGROUND_GREEN
#define CD_FG_CYAN		(FOREGROUND_GREEN | FOREGROUND_BLUE)
#define CD_FG_BLUE		FOREGROUND_BLUE
#define CD_FG_VIOLET	(FOREGROUND_RED | FOREGROUND_BLUE)
#define CD_FG_INTENSE	FOREGROUND_INTENSITY

HANDLE CD_CreateWindow(int X, int Y, int WIDTH, int HEIGHT);

void CD_Refresh(HANDLE hCD);

void CD_SetBufferChar(HANDLE hCD, int X, int Y, char CHAR, WORD ATTR);

void CD_DrawScreen(HANDLE hCD);

void CD_SetCursorPos(HANDLE hCD, int x, int y);

#endif /* __CONSOLEDRAW_H__ */